### ISSUE TITLE
Conditional constraints

### ISSUE THREAD

**Issue by ooflorent** [vslinko/vstack-validator#2]
I'm trying to create a schema with conditional constraints and I'm unable to figure out how to do it. My data looks like this:

``` js
{
  title: "some title",
  items: [
    {type: 0, foo: "foo", bar: "bar"},
    {type: 3, baz: "baz"},
    {type: 2, qux: "qux"},
  ]
}
```

I tried to do this:

``` js
schema.type("complex", {
  title: {
    notEmpty: schema.isNotEmpty(),
  },
  items: {
    minLength: schema.minLength(1),
    values: schema.list(itemSchema),
  },
})
```

Unfortunately I don't know how `itemSchema` must be declared. I have a function which retrieve a schema based on the `type` but I can't see where I could call it...

``` js
function getSchemaByType(type) {
  switch (type) {
    case 0: return someSchema
    case 1: return otherSchema
    // ...
  }
}
```

Could you point me in the right direction?

**Comment by vslinko** [comment]
Hello!

I created an example for your use-case. There is some points:
- `schema.isNotEmpty` is a fully prepared `Constraint`, you should provide it as value. In opposite `schema.minLength` is "Constraint Creator".
- You can implement _almost_ anything you want using regular function composition.

**Comment by ooflorent** [comment]
Many thanks! This is awesome. Would you mind export `Schema` from `vstack-validator`?

**Comment by vslinko** [comment]
Published version `3.1.0`

**Comment by ooflorent** [comment]
This is nice. I can now convert our (huge) codebase to `vstack-validator` and drop our `strulidator` inspired library. `ripster` was so inspiring. Thank you for your hard work exploring the JavaScript ecosystem.

On last suggestion, adding a `redux-form` layer to convert `vstack-validator` errors is a bit tricky when you have a deep and complex field structure. It would be a huge benefit to expose a helper that reduces the errors. e.g. of fields:

``` js
foo
bar[].baz
qux[].foo[].test1
qux[].foo[].test2
```

**Comment by vslinko** [comment]
Yes, we also have our internal converter. It's working for us but it's ugly :smile:

**Comment by ooflorent** [comment]
Would you please share a gist? :wink:

**Comment by vslinko** [comment]
https://gist.github.com/vslinko/ac99a4236653bc0653a3
But it isn't working with more than 1 level of nesting.

**Comment by vslinko** [comment]
And yes, we're using `asyncValidator` strategy.

**Comment by ooflorent** [comment]
Damn I just realised that it means that it's impossible to do synchronous validation because `createConstraint` returns a promise...
